	<!--[if !IE]> -->
	<script type="text/javascript" src="<%=staticFilesRoot%>js/resizetaOverlay.js" defer="defer"></script>
	<!-- <![endif]-->
	<script type="text/javascript" src="<%=staticFilesRoot%>js/getElementsBySelector.js" defer="defer"></script>
	<script type="text/javascript" src="<%=staticFilesRoot%>js/behavior.js" defer="defer"></script>
	<script type="text/javascript" src="<%=staticFilesRoot%>js/MessAdmin.js" defer="defer"></script>